server:
  port: 8086

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    org.springframework.security.oauth2: ERROR
    #    org.springframework.boot.autoconfigure: ERROR