server:
  port: 8086

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000

### Keycloak Client Config ###

# keycloak:
#   auth-server-url: http://localhost:9001/auth
#   realm: app-micro
#   resource: app-micro
#   credentials:
#     secret: 339dc07d-d357-4dc4-8648-c8d0b047ff7a
#   bearer-only: true
#   public-client: true
#   security-constraints:
#     - auth-roles:
#         - user
#       security-collections:
#         - name:
#           patterns:
#             - /user/*

### Spring Actuator Config ###

management:
  endpoints:
    web:
      exposure:
        include: '*'


### Logging Config ###

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.keycloak: TRACE
    #    org.springframework.boot.autoconfigure: DEBUG
