server:
  port: 8087

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9001/auth/realms/app-micro

### Keycloak Client Config ###

keycloak:
  auth-server-url: http://localhost:9001/auth
  realm: app-micro
  resource: app-micro
  credentials:
    secret: 6df1f480-1d3a-4a9d-8f59-f188669c0e58
  bearer-only: true
  public-client: true
  security-constraints:
    - auth-roles:
        - user
      security-collections:
        - name:
          patterns:
            - /user/*

### Spring Actuator Config ###

management:
  endpoints:
    web:
      exposure:
        include: '*'


### Logging Config ###

logging:
  level:
    root: OFF
    org.springframework.web: OFF
    org.springframework.security: OFF
    org.springframework.security.oauth2: OFF
    #    org.springframework.boot.autoconfigure: OFF