server:
  port: 8082

spring:
  security:
   oauth2:
      resourceserver:
        jwt:
         issuer-uri: http://localhost:9001/auth/realms/app-micro

### Keycloak Client Config ###

keycloak:
  auth-server-url: http://localhost:9001/auth
  realm: app-micro
  resource: app-micro
  credentials:
    secret: 4086694d-809b-40a9-8400-ef632ef62e47
  bearer-only: true
  public-client: true
  security-constraints:
    - auth-roles:
        - user
     security-collections:
        - name:
          patterns:
           - /user/*

### Spring Actuator Config ###

management:
  endpoints:
    web:
      exposure:
       include: '*'


### Logging Config ###

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.keycloak: TRACE
    #    org.springframework.boot.autoconfigure: DEBUG